---
kind: pipeline
type: docker
name: fetch

trigger:
  event:
    - push

steps:
  - name: setup
    image: gcc
    commands:
      - apk add gcc make binutils bash libc-dev libnsl-dev linux-pam-dev musl-dev
      - make build
      - make test

