---
kind: pipeline
# type: docker
name: fetch

trigger:
  event:
    - push

platform:
  arch: amd64

steps:
  # - name: setup
  #   image: gcc
  #   commands:
  #     - apk add gcc make binutils bash libc-dev musl-dev

  - name: build
    image: gcc
    commands:
      - make build

  - name: test
    image: gcc
    commands:
      - make test

