---
kind: pipeline
type: docker
name: fetch

trigger:
  event:
    - push

steps:
  - name: setup
    image: alpine:latest
    commands:
      - apk add gcc make binutils bash libc-dev musl-dev
    volumes:
      - name: shared-data
        path: /drone/shared-data

  - name: build
    image: alpine:latest
    commands:
      - make build
    volumes:
      - name: shared-data
        path: /drone/shared-data

  - name: test
    image: alpine:latest
    commands:
      - make test
    volumes:
      - name: shared-data
        path: /drone/shared-data


