---
kind: pipeline
type: docker
name: fetch

trigger:
  event:
    - push

image: alpine:latest

steps:
  - name: setup
    commands:
      - apk add gcc make binutils bash libc-dev musl-dev

  - name: build
    commands:
      - pwd
      - make build

  - name: test
    commands:
      - make test

